# MILESTONE

'''
=================================================

Milestone P0

Nama  : Zafirah Aida Adista

Batch : CODA-RMT-015

=================================================
'''

## 1. Import Libraries & Driver

In [5]:
import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup
import time

## 2. EXTRACT DATA

In [ ]:
# Mulai jalankan browser
driver = webdriver.Edge()
url = 'https://matahari.com/collections/desember-new-arrival?filter.v.m.custom.discount_group=10%25+ke+atas'

# Penarikan konten dengan infinite scroll
driver.get(url)
for i in range(5):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2) 

# Penarikan source HTML setelah konten ditampilkan
html = driver.page_source 
soup = BeautifulSoup(html, "html.parser")

# Pengambilan elemen berdasarkan tags, attribute, dan attribute_value
el_product = soup.find_all('div', {'class': 'grid-product__title'})
el_price = soup.find_all('div', {'class': 'grid-product__price'})
el_brand = soup.find_all('div', {'class': 'grid-product__vendor'})
el_diskon = soup.find_all('span', {'class': 'grid-product__price--savings'})

# List untuk menampung data mentah
product_name = []
price = []
brand = []
diskon = []

# Iterasi dari tiap elemen
for data in el_product:
    product_name.append(data.get_text())

for data in el_price:
    price_text = data.find('span').get_text().strip().strip()
    price.append(price_text)

for data in el_brand:
    brand_name = data.get_text().strip()
    brand.append(brand_name)

for data in el_diskon:
   diskon.append(data.get_text().strip().replace('-', ''))

# Menghentikan driver
driver.quit

# Konversi hasil ekstrak ke Df Pandas
df = pd.DataFrame({
    'brand' : brand,
    'product_name' : product_name,
    'diskon' : diskon,
    'price' : price})

In [ ]:
# Melihat isi konten df
df

,brand,product_name,diskon,price
0,SUKO,Suko Fine Katun Kemeja Lengan Pendek Pria,28%,Rp 179.000
1,Nevada,Nevada Boxy French Nickelodeon Spongebob Patri...,20%,Rp 160.000
2,Connexion,Connexion Basic Poly Ploi 2 Lower Waistband Ce...,15%,Rp 170.000
3,Nevada,Nevada Double Strap Buckle Slipper Sandal Pria,15%,Rp 111.000
4,Cole,Cole Graphic Puff Stich Kaos Pria,25%,Rp 89.925
...,...,...,...,...
79,Nevada,Nevada Wide Leg Ribbon Cargo Celana Panjang An...,35%,Rp 129.000
80,Little M,Little M Stretch Whisker Celana Denim Anak Lak...,34%,Rp 99.000
81,Cole,Cole Graphic Hd Awaken Rise Kaos Pria,25%,Rp 89.925
82,SUKO,Suko Graphic Kerah Bulat Raglan Kaos Anak Laki...,40%,Rp 60.000
83,ST. YVES,St. Yves Sandal Slipper Wide Strap Fq4 Wanita,20%,Rp 104.000

In [ ]:
# Menyimpan data hasil ekstraksi ke csv
df.to_csv('dataset_milestone.csv')

## 3. TRANSFORM

In [8]:
# Memuat data dari file CSV ke dalam DataFrame pandas
df = pd.read_csv('dataset_milestone.csv')

In [9]:
# Melihat isi konten df
df

,Unnamed: 0,brand,product_name,diskon,price
0,0,SUKO,Suko Fine Katun Kemeja Lengan Pendek Pria,28%,Rp 179.000
1,1,Nevada,Nevada Boxy French Nickelodeon Spongebob Patri...,20%,Rp 160.000
2,2,Connexion,Connexion Basic Poly Ploi 2 Lower Waistband Ce...,15%,Rp 170.000
3,3,Nevada,Nevada Double Strap Buckle Slipper Sandal Pria,15%,Rp 111.000
4,4,Cole,Cole Graphic Puff Stich Kaos Pria,25%,Rp 89.925
...,...,...,...,...,...
79,79,Nevada,Nevada Wide Leg Ribbon Cargo Celana Panjang An...,35%,Rp 129.000
80,80,Little M,Little M Stretch Whisker Celana Denim Anak Lak...,34%,Rp 99.000
81,81,Cole,Cole Graphic Hd Awaken Rise Kaos Pria,25%,Rp 89.925
82,82,SUKO,Suko Graphic Kerah Bulat Raglan Kaos Anak Laki...,40%,Rp 60.000
83,83,ST. YVES,St. Yves Sandal Slipper Wide Strap Fq4 Wanita,20%,Rp 104.000

In [15]:
# Menghapus kolom yang tidak diperlukan
df = df.drop(columns='Unnamed: 0')

In [16]:
# Menampilkan informasi rangkuman data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         84 non-null     object
 1   product_name  84 non-null     object
 2   diskon        84 non-null     object
 3   price         84 non-null     object
dtypes: object(4)
memory usage: 2.8+ KB

```
- Terdapat 84 rows dan 4 columns
- Tidak ada missing value pada masing-masing kolom
- Semua kolom memiliki tipe data object
```

### Cleaning kolom "diskon"

In [18]:
# Mengambil angkanya saja dengan menghilangkan '%' dan
df['diskon'] = df['diskon'].str.replace('%', '')

# Mengganti tipe data kolom menjadi int
df['diskon'] = df['diskon'].astype(int)

### Cleaning kolom "price"

In [21]:
# Mengambil angkanya saja dengan menghilangkan 'Rp' dan '.'
df['price'] = df['price'].str.replace('Rp', '').str.replace('.', '')

# Mengganti tipe data kolom menjadi int
df['price'] = df['price'].astype(int)

In [ ]:
# Memastikan tipe data kolom "diskon" dan "price" sudah berubah menjadi int
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         84 non-null     object
 1   product_name  84 non-null     object
 2   diskon        84 non-null     int64
 3   price         84 non-null     int64
dtypes: int64(2), object(2)
memory usage: 2.8+ KB

kolom "diskon" dan "price" berhasil diubah menjadi int

In [ ]:
# Menampilkan index list dataframe
df.index

RangeIndex(start=0, stop=84, step=1)

In [ ]:
# Menampilkan nilai unique masing-masing kolom
df.nunique()

brand            8
product_name    83
diskon          12
price           36
dtype: int64

In [31]:
# Menyimpan output data preparation ke csv
df.to_csv('coda_P0M1_zafirah_aida.csv')